### ISSUE TITLE
I get asked to activate my licence every day

### ISSUE THREAD

**Issue by sheli21** [rupok/essential-addons-elementor-lite#157]

**Comment by sheli21** [comment]
There is something wrong with plugin. I bought the lifetime licence. I get asked every day to enter the licence key. This is really annoying. Please can you look into it. Thank you

**Comment by rupok** [comment]
Hello @sheli21 

I guess you are using pro version. Please update to v2.9.2 and hopefully it won't happen again.

Let me know if you still see such issue.

Thanks!

**Comment by sheli21** [comment]
I have updated it and this doesnt make any difference

**Comment by sheli21** [comment]
It says there is an automatic update available but wont update

**Comment by sheli21** [comment]
<img width="1111" alt="screen shot 2019-01-24 at 10 56 26" src="https://user-images.githubusercontent.com/20577455/51666537-c9bb6d00-1fc6-11e9-9136-45ee847524f9.png">

**Comment by sheli21** [comment]
<img width="1268" alt="screen shot 2019-01-24 at 10 57 57" src="https://user-images.githubusercontent.com/20577455/51666596-eeafe000-1fc6-11e9-9c57-04212e7bb628.png">

**Comment by sheli21** [comment]
please help me!!

**Comment by rupok** [comment]
Hi @ sheli21 

Please initiate a live chat from our site https://wpdeveloper.net and we will help you to solve this.

**Comment by Heyamandar** [comment]
Same problem here. This is on my clients site and is VERY embarrassing. The plugin IS UP TO DATE. So, that's not the issue. But, I have to ACTIVE the license every time I log in - daily. Makes no sense. I have started to look at other options because I can't have this happening. It's unprofessional.

**Comment by rupok** [comment]
Hello @Heyamandar 

It has been fixed from v2.14.1. Please update manually if you don't see the update notification for this version.

Thanks!

**Comment by vgstef** [comment]
Hi! 
I've updated to v2.14.1 and I still get asked to activate my licence. It happens each time I switch the language with WPML (in the backend). Maybe a conflict? Or maybe your plugin doesn't recognize the new URL (WPML adds "&lang=en")?

**Comment by rupok** [comment]
Hi @vgstef can you open a support ticket so we could investigate and assist?

**Comment by SYNRZReaper** [comment]
I am using version 3.0.0 and it happened to me this morning. The only reason I am commenting on here is because within your plugin, you can submit bugs to GitHub
